# Generated by Django 4.2 on 2024-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
